import { MenuItem, BeanOrigin, CafeLocation } from '@/types';

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 'm1',
    name: 'Obsidian Reserve Espresso',
    subtitle: 'Micro-lot Double Shot',
    description: 'Extracted from rare Chikmagalur high-altitude shade-grown Arabica beans. Bright bergamot aroma with intense dark chocolate finish and velvety crema.',
    price: 240,
    category: 'espresso',
    origin: 'Chikmagalur, Karnataka',
    roastLevel: 'Medium',
    tags: ['Signature', 'Single-Origin', 'Vegan'],
    image: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&w=800&q=80',
    calories: 10,
    prepTime: '3 mins',
    rating: 4.9,
    reviewsCount: 142,
    isBestseller: true,
  },
  {
    id: 'm2',
    name: 'Smoked Vanilla Cold Drip',
    subtitle: '24-Hour Slow Extraction',
    description: 'Brewed drop-by-drop over 24 hours through Japanese ice towers, infused with organic Araku Valley beans, Madagascar bourbon vanilla, and applewood smoke.',
    price: 320,
    category: 'cold-crafts',
    origin: 'Araku Valley, Andhra Pradesh',
    roastLevel: 'Light',
    tags: ['Cold Brew', 'Artisanal', 'Bestseller'],
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=800&q=80',
    calories: 45,
    prepTime: 'Immediate',
    rating: 5.0,
    reviewsCount: 218,
    isBestseller: true,
  },
  {
    id: 'm3',
    name: 'V60 Crystal Pour-Over',
    subtitle: 'Hand-Crafted Geisha',
    description: 'Precision hand pour using Chemex V60 paper filter. Reveals delicate white floral notes, nectarine sweetness, and silky tea-like body from Coorg highlands.',
    price: 420,
    category: 'pour-over',
    origin: 'Coorg Reserve, Karnataka',
    roastLevel: 'Light',
    tags: ['Rare Micro-Lot', 'Award Winner'],
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
    calories: 5,
    prepTime: '6 mins',
    rating: 4.95,
    reviewsCount: 96,
    isNew: true,
  },
  {
    id: 'm4',
    name: 'Gold Leaf Charcoal Latte',
    subtitle: 'Activated Charcoal & Oat Milk',
    description: 'A striking obsidian black latte crafted with Wayanad highland beans, activated coconut charcoal, silky steamed oat milk, real edible 24k gold flakes, and lavender blossom syrup.',
    price: 380,
    category: 'signature-latte',
    origin: 'Wayanad Hills, Kerala',
    roastLevel: 'Medium',
    tags: ['Superfood', 'Instagrammable', 'Dairy-Free'],
    image: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=800&q=80',
    calories: 140,
    prepTime: '4 mins',
    rating: 4.88,
    reviewsCount: 310,
    isBestseller: true,
  },
  {
    id: 'm5',
    name: 'Salted Honey Oat Flat White',
    subtitle: 'Himalayan Pink Salt & Wildflower Honey',
    description: 'Velvety micro-foam poured over a ristretto espresso base from Baba Budangiri Estate, sweetened with wild mountain honey and balanced with Himalayan salt.',
    price: 290,
    category: 'espresso',
    origin: 'Baba Budangiri, Chikmagalur',
    roastLevel: 'Dark',
    tags: ['Creamy', 'Barista Pick'],
    image: 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&w=800&q=80',
    calories: 160,
    prepTime: '4 mins',
    rating: 4.82,
    reviewsCount: 175,
  },
  {
    id: 'm6',
    name: 'Nitro Cloud Brew',
    subtitle: 'Nitrogen-Infused Cold Draft',
    description: 'Silky smooth draft cold brew crafted with Nilgiri biosphere high-altitude beans, infused with pure nitrogen gas for cascading micro-bubbles and natural sweetness.',
    price: 340,
    category: 'cold-crafts',
    origin: 'Nilgiri Hills, Tamil Nadu',
    roastLevel: 'Medium',
    tags: ['Draft Brew', 'Zero Sugar'],
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=800&q=80',
    calories: 15,
    prepTime: 'Immediate',
    rating: 4.91,
    reviewsCount: 154,
  },
  {
    id: 'm7',
    name: 'Pistachio Saffron Croissant',
    subtitle: '72-Hour Laminated French Pastry',
    description: 'Flaky Golden AOP Butter Croissant filled with rich Iranian pistachio praline paste, infused with Kashmir saffron glaze and topped with crushed pistachios.',
    price: 280,
    category: 'artisan-bakery',
    tags: ['Freshly Baked', 'Decadent'],
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80',
    calories: 320,
    prepTime: 'Warm on request',
    rating: 4.97,
    reviewsCount: 280,
    isBestseller: true,
  },
  {
    id: 'm8',
    name: 'Valrhona Truffle Danish',
    subtitle: 'Dark Chocolate & Hazelnut Flake',
    description: 'Decadent double-chocolate Danish made with 70% Valrhona Guanaja dark chocolate ganache and roasted hazelnut praline dust.',
    price: 290,
    category: 'artisan-bakery',
    tags: ['Organic', 'Pastry Chef Special'],
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    calories: 360,
    prepTime: 'Warm on request',
    rating: 4.89,
    reviewsCount: 164,
  },
  {
    id: 'm9',
    name: 'Chikmagalur Bloom (250g Whole Bean)',
    subtitle: 'Single Origin Micro-Lot Bag',
    description: 'Light-roasted shade-grown Baba Budangiri beans with tasting notes of jasmine flower, honeydew melon, and sparkling citrus acidity. Ideal for V60 & Chemex.',
    price: 850,
    category: 'beans-merch',
    origin: 'Chikmagalur, Karnataka',
    roastLevel: 'Light',
    tags: ['Whole Beans', 'Micro-Lot'],
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=800&q=80',
    rating: 4.96,
    reviewsCount: 88,
  },
  {
    id: 'm10',
    name: 'Araku Reserve Blend (250g)',
    subtitle: 'Signature Organic Dark Roast',
    description: 'Our award-winning flagship espresso blend combining high-elevation Araku Valley and Coorg Arabica beans. Heavy body, dark cacao, and roasted caramel notes.',
    price: 750,
    category: 'beans-merch',
    origin: 'Araku & Coorg Blend',
    roastLevel: 'Dark',
    tags: ['House Specialty', 'Whole Beans'],
    image: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?auto=format&fit=crop&w=800&q=80',
    rating: 4.93,
    reviewsCount: 204,
  },
];

export const BEAN_ORIGINS: BeanOrigin[] = [
  {
    id: 'chikmagalur',
    country: 'India',
    region: 'Chikmagalur, Karnataka',
    farm: 'Baba Budangiri Estate (1,900m ASL)',
    altitude: '1,800 - 1,950m ASL',
    cuppingScore: 92.5,
    processMethod: 'Shade-Grown Natural Sun-Dried',
    notes: ['Jasmine Blossom', 'Bergamot Citrus', 'Dark Cocoa', 'Spice Finish'],
    tasteProfile: {
      body: 78,
      acidity: 90,
      sweetness: 88,
      aroma: 96,
    },
    roastingCurveData: [
      { time: '0m', temp: 180 },
      { time: '3m', temp: 140 },
      { time: '6m', temp: 175 },
      { time: '9m', temp: 198 },
      { time: '11m', temp: 208 },
    ],
    description: 'Cultivated at Baba Budangiri—the historic birthplace of Indian coffee—Chikmagalur Arabica is celebrated for its floral perfume, bright tea-like clarity, and rich stone fruit sweetness.',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    coordinates: { x: 55, y: 58 },
  },
  {
    id: 'araku',
    country: 'India',
    region: 'Araku Valley, Andhra Pradesh',
    farm: 'Eastern Ghats Tribal Organic Micro-Lot',
    altitude: '1,400 - 1,600m ASL',
    cuppingScore: 91.8,
    processMethod: 'Anaerobic Fermentation (48 hours)',
    notes: ['Red Apple', 'Toffee Cacao', 'Wild Honey', 'Juicy Plum'],
    tasteProfile: {
      body: 85,
      acidity: 80,
      sweetness: 92,
      aroma: 88,
    },
    roastingCurveData: [
      { time: '0m', temp: 185 },
      { time: '3m', temp: 145 },
      { time: '6m', temp: 180 },
      { time: '9m', temp: 205 },
      { time: '12m', temp: 216 },
    ],
    description: 'Grown organically by indigenous farmer cooperatives in the Eastern Ghats, Araku Valley beans deliver luxurious sweetness, low bitterness, and chocolate praline undertones.',
    image: 'https://images.unsplash.com/photo-1524350876685-274059332603?auto=format&fit=crop&w=800&q=80',
    coordinates: { x: 62, y: 55 },
  },
  {
    id: 'coorg',
    country: 'India',
    region: 'Coorg (Kodagu), Karnataka',
    farm: 'Western Ghats Canopy Estate',
    altitude: '1,650 - 1,800m ASL',
    cuppingScore: 90.2,
    processMethod: 'Washed under Cardamom & Pepper Canopy',
    notes: ['Dark Chocolate', 'Spiced Nutmeg', 'Cardamom Zest', 'Caramel'],
    tasteProfile: {
      body: 88,
      acidity: 75,
      sweetness: 86,
      aroma: 92,
    },
    roastingCurveData: [
      { time: '0m', temp: 190 },
      { time: '3m', temp: 150 },
      { time: '6m', temp: 185 },
      { time: '9m', temp: 208 },
      { time: '12m', temp: 220 },
    ],
    description: 'Shade-grown under a dense canopy of pepper vines, orange trees, and cardamom, Coorg micro-lots produce dense beans featuring spicy cocoa aromas and full-bodied depth.',
    image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
    coordinates: { x: 54, y: 60 },
  },
  {
    id: 'wayanad',
    country: 'India',
    region: 'Wayanad, Kerala',
    farm: 'Highland Monsoon Reserve',
    altitude: '1,300 - 1,550m ASL',
    cuppingScore: 89.4,
    processMethod: 'Monsooned Wet-Hulled Process',
    notes: ['Cedar Wood', 'Dark Cacao', 'Pipe Tobacco', 'Wild Honey'],
    tasteProfile: {
      body: 94,
      acidity: 50,
      sweetness: 80,
      aroma: 84,
    },
    roastingCurveData: [
      { time: '0m', temp: 195 },
      { time: '3m', temp: 155 },
      { time: '6m', temp: 190 },
      { time: '9m', temp: 212 },
      { time: '13m', temp: 225 },
    ],
    description: 'Exposed to monsoon winds on the Malabar coast, Wayanad coffee has mellow low acidity, heavy syrupy body, and warm spicy undertones.',
    image: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=800&q=80',
    coordinates: { x: 53, y: 62 },
  },
];

export const CAFE_LOCATIONS: CafeLocation[] = [
  {
    id: 'loc-1',
    name: 'Brew Haven Flagship & Roastery',
    address: '100ft Road, 12th Main, Indiranagar',
    city: 'Bengaluru, Karnataka 560038',
    phone: '+91 98765 43210',
    hours: 'Mon - Sun: 7:00 AM - 11:00 PM',
    isOpenNow: true,
    seatingCapacity: 75,
    currentOccupancy: 68,
    image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80',
    features: ['On-Site Drum Roastery', 'Espresso Tasting Bar', 'High-Speed Wi-Fi', 'Glasshouse Botanical Garden'],
    coordinates: { lat: 12.9784, lng: 77.6408 },
  },
  {
    id: 'loc-2',
    name: 'Brew Haven Heritage Lounge',
    address: 'Kala Ghoda Arts Precinct, Fort',
    city: 'Mumbai, Maharashtra 400001',
    phone: '+91 98765 43211',
    hours: 'Mon - Sun: 7:30 AM - 11:30 PM',
    isOpenNow: true,
    seatingCapacity: 90,
    currentOccupancy: 42,
    image: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=800&q=80',
    features: ['Colonial Arch Sanctuary', 'Cold Brew Bar', 'Acoustic Jazz Evenings', 'Valet Parking'],
    coordinates: { lat: 18.9276, lng: 72.8331 },
  },
  {
    id: 'loc-3',
    name: 'Brew Haven Lakefront Reserve',
    address: 'Hauz Khas Village, Near Fort Ruin',
    city: 'New Delhi 110016',
    phone: '+91 98765 43212',
    hours: 'Mon - Sun: 8:00 AM - 10:30 PM',
    isOpenNow: true,
    seatingCapacity: 60,
    currentOccupancy: 85,
    image: 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=800&q=80',
    features: ['Lakefront Sunset Terrace', 'Silent Work Pods', 'Custom Pour-Over Bar', 'Coffee Masterclasses'],
    coordinates: { lat: 28.5539, lng: 77.1943 },
  },
];

export const TESTIMONIALS = [
  {
    id: 't1',
    author: 'Aarav Sharma',
    role: 'Editor, Specialty Coffee India',
    content: 'Brew Haven is a shrine to precision roasting. Their Chikmagalur Baba Budangiri V60 pour-over in Indiranagar redefined single-origin coffee for me.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 't2',
    author: 'Meera Nair',
    role: 'Architect & Interior Strategist',
    content: 'The interplay of dark obsidian stone, warm brass accents, and the scent of fresh Araku Valley beans makes Kala Ghoda Brew Haven my daily sanctuary.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 't3',
    author: 'Rohan Mehta',
    role: 'Founder, TechCraft Studio',
    content: 'From their custom online brew lab to the VIP table reservation pass, every detail is engineered to absolute perfection.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
  },
];
